// ml_norm_params.h is generated by firmware/scripts/gen_norm_params_h.py.
// Include it only here — it contains static const arrays.
#include "ml/norm_params.h"
#include "ml/normalize.h"

void ml_normalize_features(float *features) {
    for (int i = 0; i < ML_N_FEATURES; i++) {
        features[i] = (features[i] - ML_FEAT_MEAN[i]) / ML_FEAT_STD[i];
    }
}
