import argparse
import numpy as np
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("stats_npy", type=Path, help="Path to feature_stats.npy")
parser.add_argument("output_h",  type=Path, help="Path to write the header file")
args = parser.parse_args()

stats = np.load(args.stats_npy)
if stats.ndim != 2 or stats.shape[0] != 2:
    raise SystemExit(f"Expected shape (2, N), got {stats.shape}")

means = stats[0]
stds  = stats[1]
n     = len(means)

def fmt(values):
    return ",\n    ".join(f"{v:.8e}f" for v in values)

header = f"""\
#ifndef ML_NORM_PARAMS_H
#define ML_NORM_PARAMS_H

// DO NOT EDIT MANUALLY
// Auto-generated by scripts/gen_norm_params_h.py.

#define ML_N_FEATURES {n}

// Include this header only in normalize.c (static arrays).
static const float ML_FEAT_MEAN[{n}] = {{
    {fmt(means)}
}};

static const float ML_FEAT_STD[{n}] = {{
    {fmt(stds)}
}};

#endif  // ML_NORM_PARAMS_H
"""

args.output_h.parent.mkdir(parents=True, exist_ok=True)
args.output_h.write_text(header)
print(f"Written {args.output_h}  ({n} features)")

